sudo: false
language: ruby
cache: bundler
rvm:
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - 2.6.7
  - 2.7.3
  - 3.0.1
  - ruby-head
  - jruby-1.7
  - jruby-9
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
before_install:
  - gem update bundler
